import type { ElementRef } from "../types";

/** CSS.escape is present in every Chrome that supports MV3, but guard anyway. */
function escapeIdent(value: string): string {
  if (typeof CSS !== "undefined" && typeof CSS.escape === "function") {
    return CSS.escape(value);
  }
  return value.replace(/[^a-zA-Z0-9_-]/g, (c) => "\\" + c);
}

/** Escaping for the inside of an attribute selector's quoted string. */
function escapeAttrValue(value: string): string {
  return value.replace(/(["\\])/g, "\\$1");
}

function nthOfType(el: Element): number {
  let n = 1;
  let sib = el.previousElementSibling;
  while (sib) {
    if (sib.tagName === el.tagName) n++;
    sib = sib.previousElementSibling;
  }
  return n;
}

/**
 * A structural selector, e.g. `html > body:nth-of-type(1) > div:nth-of-type(2)`.
 *
 * Deliberately NOT XPath and deliberately not class-based: class names are
 * regenerated by CSS-in-JS on every build, and XPath breaks on a single
 * inserted node. nth-of-type at least survives sibling insertions of other tags.
 */
export function structuralPath(el: Element): string {
  const parts: string[] = [];
  let node: Element | null = el;
  while (node && node.nodeType === Node.ELEMENT_NODE && node !== document.documentElement) {
    parts.unshift(node.tagName.toLowerCase() + ":nth-of-type(" + nthOfType(node) + ")");
    node = node.parentElement;
  }
  return parts.length ? "html > " + parts.join(" > ") : "html";
}

/** Records every way we might find this element again. */
export function describe(el: Element): ElementRef {
  const ref: ElementRef = { path: structuralPath(el) };

  const id = el.getAttribute("id");
  // Only worth storing if it is actually unique and not obviously generated.
  if (id && !/^[a-z]*[0-9a-f]{8,}$/i.test(id)) {
    try {
      if (document.querySelectorAll("#" + escapeIdent(id)).length === 1) ref.id = id;
    } catch {
      /* malformed id, skip */
    }
  }

  const name = el.getAttribute("name");
  if (name) {
    try {
      const sel = '[name="' + escapeAttrValue(name) + '"]';
      if (document.querySelectorAll(sel).length === 1) ref.name = name;
    } catch {
      /* skip */
    }
  }

  return ref;
}

/** Tries each recorded strategy in order of durability. */
export function resolve(ref: ElementRef): Element | null {
  if (ref.id) {
    try {
      const el = document.querySelector("#" + escapeIdent(ref.id));
      if (el) return el;
    } catch { /* ignore */ }
  }
  if (ref.name) {
    try {
      const el = document.querySelector('[name="' + escapeAttrValue(ref.name) + '"]');
      if (el) return el;
    } catch { /* ignore */ }
  }
  try {
    return document.querySelector(ref.path);
  } catch {
    return null;
  }
}

/** Normalised, truncated text - used to check an anchor still means the same thing. */
export function textOf(el: Element, max = 120): string {
  return (el.textContent || "").replace(/\s+/g, " ").trim().slice(0, max);
}
