import type { ElementRef } from "../types";

/** CSS.escape is present in every Chrome that supports MV3, but guard anyway. */
function escapeIdent(value: string): string {
  if (typeof CSS !== "undefined" && typeof CSS.escape === "function") {
    return CSS.escape(value);
  }
  return value.replace(/[^a-zA-Z0-9_-]/g, (c) => "\\" + c);
}

/** Escaping for the inside of an attribute selector's quoted string. */
function escapeAttrValue(value: string): string {
  return value.replace(/(["\\])/g, "\\$1");
}

function nthOfType(el: Element): number {
  let n = 1;
  let sib = el.previousElementSibling;
  while (sib) {
    if (sib.tagName === el.tagName) n++;
    sib = sib.previousElementSibling;
  }
  return n;
}

/** Separates one shadow tree from the next inside a stored path. */
const SHADOW = " >>> ";

/** The path of an element within its own tree, stopping at that tree's root. */
function pathWithinTree(el: Element): string {
  const inShadow = el.getRootNode() instanceof ShadowRoot;
  const parts: string[] = [];
  let node: Element | null = el;

  while (node && node.nodeType === Node.ELEMENT_NODE) {
    if (!inShadow && node === document.documentElement) break;
    parts.unshift(node.tagName.toLowerCase() + ":nth-of-type(" + nthOfType(node) + ")");
    node = node.parentElement; // null at a shadow root's direct child
  }

  if (inShadow) return parts.join(" > ");
  return parts.length ? "html > " + parts.join(" > ") : "html";
}

/**
 * A structural selector, e.g. `html > body:nth-of-type(1) > div:nth-of-type(2)`,
 * with ` >>> ` marking a hop into an open shadow root.
 *
 * Deliberately NOT XPath and deliberately not class-based: class names are
 * regenerated by CSS-in-JS on every build, and XPath breaks on a single
 * inserted node. nth-of-type at least survives sibling insertions of other tags.
 */
export function structuralPath(el: Element): string {
  const segments: string[] = [];
  let current: Element | null = el;

  while (current) {
    segments.unshift(pathWithinTree(current));
    const root = current.getRootNode();
    current = root instanceof ShadowRoot ? root.host : null;
  }
  return segments.join(SHADOW);
}

function resolvePath(path: string): Element | null {
  const segments = path.split(SHADOW);
  let scope: ParentNode | null = document;
  let found: Element | null = null;

  for (const segment of segments) {
    if (!scope) return null;
    try {
      found = scope.querySelector(segment);
    } catch {
      return null;
    }
    if (!found) return null;
    scope = found.shadowRoot;
  }
  return found;
}

/**
 * Records every way we might find this element again.
 *
 * id and name are only recorded when they are unique WITHIN THE ELEMENT'S OWN
 * TREE. Inside a shadow root that is the guarantee the platform gives, and ids
 * repeat freely across component instances - so a document-wide lookup would
 * happily hand back the wrong instance's field.
 */
export function describe(el: Element): ElementRef {
  const ref: ElementRef = { path: structuralPath(el) };
  const root = el.getRootNode();
  const tree: ParentNode = root instanceof ShadowRoot ? root : document;
  const inShadow = root instanceof ShadowRoot;

  const id = el.getAttribute("id");
  // Only worth storing if it is actually unique and not obviously generated.
  if (id && !/^[a-z]*[0-9a-f]{8,}$/i.test(id)) {
    try {
      // In a shadow tree the id is scoped to that tree, so it cannot be used as
      // a document-wide shortcut on the way back.
      if (!inShadow && tree.querySelectorAll("#" + escapeIdent(id)).length === 1) ref.id = id;
    } catch {
      /* malformed id, skip */
    }
  }

  const name = el.getAttribute("name");
  if (name && !inShadow) {
    try {
      const sel = '[name="' + escapeAttrValue(name) + '"]';
      if (tree.querySelectorAll(sel).length === 1) ref.name = name;
    } catch {
      /* skip */
    }
  }

  return ref;
}

/** Tries each recorded strategy in order of durability. */
export function resolve(ref: ElementRef): Element | null {
  if (ref.id) {
    try {
      const el = document.querySelector("#" + escapeIdent(ref.id));
      if (el) return el;
    } catch { /* ignore */ }
  }
  if (ref.name) {
    try {
      const el = document.querySelector('[name="' + escapeAttrValue(ref.name) + '"]');
      if (el) return el;
    } catch { /* ignore */ }
  }
  return resolvePath(ref.path);
}

/** Normalised, truncated text - used to check an anchor still means the same thing. */
export function textOf(el: Element, max = 120): string {
  return (el.textContent || "").replace(/\s+/g, " ").trim().slice(0, max);
}
